namespace:
  name: sandbox
 
image:
  repository: maabdelfattah/techtrends 
  tag: latest
  pullPolicy: IfNotPresent
  
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

replicaCount: 1
containerPort: 3111
livenessProbePath: /healthz
readinessProbePath: /healthz

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
